### ISSUE TITLE
Remove olinalumni.org/banter

### ISSUE THREAD

**Issue by gregmarra** [olinalumni/olinalumni.github.io#127]
Where is this being served from? How is that configured?

**Comment by gregmarra** [comment]
Being served by 151.101.24.133

**Comment by gregmarra** [comment]
Oh maybe it serves https://github.com/olinalumni/banter

**Comment by tcr** [comment]
@gregmarra Want to just mention how this is being linked in the README and close?

**Comment by gregmarra** [comment]
Yea will do that.

**Comment by skier31415** [comment]
This is not a publicly digestible page, not sure why it was ever hosted on olinalumni.org.

Looks like you can disable the link on settings/options of the repo (I don't have access), or I can push a redirect to the other repo to link to /resources/banter.

**Comment by gregmarra** [comment]
@skier31415 can you show me specifically what to do?

**Comment by skier31415** [comment]
Not sure exactly how it's configured for this repo, but this is what it looks like on my repos.  Be sure to hit "save" after disabling (wasn't obvious for me).
![screen shot 2016-08-29 at 7 19 20 pm](https://cloud.githubusercontent.com/assets/1082028/18070731/d4b2a910-6e1d-11e6-9f0d-2c9671d7cb69.png)
![screen shot 2016-08-29 at 7 20 14 pm](https://cloud.githubusercontent.com/assets/1082028/18070732/d4b35770-6e1d-11e6-8174-084a9accc682.png)

**Comment by skier31415** [comment]
Did you try this ?  Should be pretty easy :)

**Comment by gregmarra** [comment]
I'm not able to disable this.

![image](https://cloud.githubusercontent.com/assets/57101/18697911/b73e8f0c-7f7a-11e6-93be-c6476151025a.png)

Any idea why that might be?

**Comment by skier31415** [comment]
Weird.  As per 

https://help.github.com/articles/unpublishing-a-project-pages-site/

we can just delete the branch on the underlying repo.  Or we can probably just delete the repo.  Only @segalova and @mcolyer have contributed to that, and again, not supposed to be publicly consumable, so I say it's safe to delete.  Not sure how to assign this issue to them, but they're mentioned, so maybe they can delete it :)

**Comment by mcolyer** [comment]
@skier31415 I'll just go ahead and delete the repo. It was from Banter was setup a long time ago and it ended up not getting used.

**Comment by skier31415** [comment]
@gregmarra this issue can be closed :)
